// <auto-generated />
using System;
using GestionProduits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIBLIOGEST.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224085839_FixSeedDate")]
    partial class FixSeedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionProduits.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Auteur");

                    b.HasIndex("Categorie");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Nom");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Auteur = "Antoine de Saint-Exupéry",
                            Categorie = "Roman",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Un conte philosophique et poétique sous l'apparence d'un conte pour enfants.",
                            Fournisseur = "Gallimard",
                            ISBN = "978-2-07-040850-4",
                            Nom = "Le Petit Prince",
                            Prix = 12.50m,
                            QuantiteStock = 45
                        },
                        new
                        {
                            Id = 2,
                            Auteur = "George Orwell",
                            Categorie = "Science-Fiction",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Roman dystopique décrivant une société totalitaire.",
                            Fournisseur = "Folio",
                            ISBN = "978-2-07-036822-8",
                            Nom = "1984",
                            Prix = 8.90m,
                            QuantiteStock = 28
                        },
                        new
                        {
                            Id = 3,
                            Auteur = "Victor Hugo",
                            Categorie = "Roman",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Chef-d'œuvre de la littérature française du XIXe siècle.",
                            Fournisseur = "Le Livre de Poche",
                            ISBN = "978-2-253-00496-8",
                            Nom = "Les Misérables",
                            Prix = 15.00m,
                            QuantiteStock = 12
                        },
                        new
                        {
                            Id = 4,
                            Auteur = "J.K. Rowling",
                            Categorie = "Fantaisie",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Premier tome de la saga Harry Potter.",
                            Fournisseur = "Gallimard Jeunesse",
                            ISBN = "978-2-07-054127-0",
                            Nom = "Harry Potter à l'école des sorciers",
                            Prix = 18.50m,
                            QuantiteStock = 65
                        },
                        new
                        {
                            Id = 5,
                            Auteur = "Robert C. Martin",
                            Categorie = "Informatique",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Guide pratique pour écrire du code propre et maintenable.",
                            Fournisseur = "Pearson",
                            ISBN = "978-0-13-235088-4",
                            Nom = "Clean Code",
                            Prix = 45.00m,
                            QuantiteStock = 8
                        },
                        new
                        {
                            Id = 6,
                            Auteur = "Yuval Noah Harari",
                            Categorie = "Histoire",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Une brève histoire de l'humanité.",
                            Fournisseur = "Albin Michel",
                            ISBN = "978-2-226-25710-4",
                            Nom = "Sapiens",
                            Prix = 24.00m,
                            QuantiteStock = 32
                        },
                        new
                        {
                            Id = 7,
                            Auteur = "Eiichiro Oda",
                            Categorie = "Manga",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Le début des aventures de Luffy.",
                            Fournisseur = "Glénat",
                            ISBN = "978-2-7234-3329-7",
                            Nom = "One Piece Tome 1",
                            Prix = 6.90m,
                            QuantiteStock = 0
                        },
                        new
                        {
                            Id = 8,
                            Auteur = "Sun Tzu",
                            Categorie = "Histoire",
                            DateCreation = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Traité de stratégie militaire chinois.",
                            Fournisseur = "Flammarion",
                            ISBN = "978-2-08-070508-0",
                            Nom = "L'Art de la Guerre",
                            Prix = 5.90m,
                            QuantiteStock = 22
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
